#!/bin/bash
#Christopher Rogers
#Lab 3

header='<html>
<body> 
<h1> Failed Login Attempts Report as of'
footer='</html>
</body>'
endhead='</h1>'

echo $header >> ~/public_html/flog.html
date '+%A, %B, %d, %Y' >> ~/public_html/flog.html
echo $endhead >> ~/public_html/flog.html

awk '{ print $6 " " $7 " " $8 " " $9 " " $10 " " $11}' $1 \
 | grep "Failed password for" | awk '{print $4}' \
 | sort | uniq -c | sort -k1,1rn -k2.1 \
 | sed 's/^/<br \/>/g' \
 | sed 's/invalid/\&lt;UNKNOWN\&gt;/g' >> ~/public_html/flog.html 

echo $footer >> ~/public_html/flog.html

chmod 755 ~/public_html/flog.html

exit 0
